### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by da2022** [fboyle2001/SixthFormApp#24]
Basically all Mr skillet said

**Comment by fboyle2001** [comment]
http://docs.phonegap.com/tutorials/develop/push-notifications/ this the documentation for push notifications. Will definitely have to look into it.

**Comment by fboyle2001** [comment]
127cc4b145b2027757a04ccb14d3e55d45ec5f4a, e50e216e1fece6b5bd3319107db3cd0b3a3a7373, d3e1b9c04cff49958955075410a83260c8b32136
