### ISSUE TITLE
Make Files Auto Delete

### ISSUE THREAD

**Issue by fboyle2001** [fboyle2001/SixthFormApp#25]
Feedback from presentation

**Comment by CashMeister** [comment]
At the moment the View Latest Notices links still has a file which is past its expiry date; it has been removed from the table though.   This should be fixed when the file automatically delete

**Comment by fboyle2001** [comment]
Yeah i'm not too sure how to go about this. The options I have thought of are:
- Each time a file is uploaded, search and delete all files past their expiry date (or when users login etc.)
- Setup an automatic task on the server's operating system to delete the files

**Comment by fboyle2001** [comment]
@CashMeister I think that can fixed without deleting the files and it shouldn't be happening at the moment. I've raised a separate issue for that (#28)

**Comment by fboyle2001** [comment]
Added in d6ea51085e22ebdbf8a5bfc0a1ee5145afdde79e which will auto delete old files when an admin logs in
