### ISSUE TITLE
Links keep displaying once the expiry data has finished 

### ISSUE THREAD

**Issue by CashMeister** [fboyle2001/SixthFormApp#7]

**Comment by fboyle2001** [comment]
I think I know what is wrong I’ll fix it when I’m home

**Comment by fboyle2001** [comment]
The issue has been fixed (see commit b42e485f5031ec62323125104c8d78273d14db8d) by using the validOnly parameter.

**Comment by fboyle2001** [comment]
The issue has been fixed (see commit b42e485f5031ec62323125104c8d78273d14db8d) by using the validOnly parameter.
